version: '3'

services:
  cms:
    build:
      context: .
      target: local
    container_name: sk-cms
    working_dir: /app
    restart: unless-stopped
    ports:
      - '4000:4000'
    depends_on:
      - db
    volumes:
      - ./config:/app/config
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./.env.local:/app/.env
      - ./public/uploads:/app/public/uploads
      - ./data:/app/data

  db:
    image: postgres
    command: postgres -c 'max_connections=200'
    container_name: sk-db
    restart: unless-stopped
    env_file: ".env.local"
    volumes:
      - sk-db-pgdata:/var/lib/postgresql/data

volumes:
  sk-db-pgdata:

